jobs:
  - job: Build
    steps:
      - task: PowerShell@2
        enabled: true
        displayName: "Install dependencies"
        inputs:
          targetType: 'inline'
          script: 'npm ci'
          workingDirectory: tests/ # update accordingly
 
      - script: npx playwright install --with-deps
        displayName: "Install Playwright Browsers"
 
      - task: AzureCLI@2
        displayName: Run Playwright Tests on All Browsers
        env:
          PLAYWRIGHT_SERVICE_URL: $(PLAYWRIGHT_SERVICE_URL)
          PLAYWRIGHT_SERVICE_RUN_ID: $(Build.DefinitionName) - $(Build.BuildNumber) - $(System.JobAttempt)
        inputs:
          azureSubscription: 'kuletsky-soft' # Service connection used to authenticate this pipeline with Azure to use the service
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            npm run test:playwright:all         
          addSpnToEnvironment: true

      - script: |
          npm run test:cucumber:all
        displayName: "Run Cucumber Tests on All Browsers"
        continueOnError: true
          
 
      - task: PublishPipelineArtifact@1
        displayName: Upload Playwright report
        inputs:
          targetPath: test/playwright-report
          artifact: 'Playwright tests'
          publishLocation: 'pipeline'